create table if not exists public.customers (
  id text primary key,
  name text not null,
  contact_name text not null,
  contact_email text not null,
  initials text not null,
  plan text not null,
  health_score integer not null check (health_score between 0 and 100),
  risk_level text not null check (risk_level in ('High', 'Medium', 'Low')),
  renewal_days integer not null,
  last_activity_label text not null,
  usage_change_percent integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id bigint primary key,
  customer_id text not null references public.customers(id) on delete cascade,
  subject text not null,
  preview text not null,
  body text not null,
  display_time text not null,
  unread boolean not null default true,
  intent text not null,
  received_at timestamptz not null default now()
);

create table if not exists public.customer_usage (
  customer_id text primary key references public.customers(id) on delete cascade,
  active_users integer not null,
  licensed_seats integer not null,
  weekly_active_users_change_percent integer not null,
  last_meaningful_activity_days_ago integer not null,
  trend_window text not null
);

create table if not exists public.subscriptions (
  customer_id text primary key references public.customers(id) on delete cascade,
  status text not null,
  monthly_value_usd integer not null,
  renewal_in_days integer not null,
  cancel_at_period_end boolean not null default false,
  available_retention_credit_usd integer not null default 0
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  customer_id text not null references public.customers(id) on delete cascade,
  subject text not null,
  status text not null,
  priority text not null,
  opened_days_ago integer not null default 0
);

create table if not exists public.agent_runs (
  id uuid primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  customer_id text not null references public.customers(id) on delete cascade,
  mode text not null,
  model text,
  status text not null,
  result jsonb not null,
  trace jsonb not null,
  tool_call_count integer not null,
  model_turns integer not null,
  duration_ms integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.approvals (
  id text primary key,
  agent_run_id uuid references public.agent_runs(id) on delete set null,
  customer_id text not null references public.customers(id) on delete cascade,
  customer_name text not null,
  customer_initials text not null,
  action text not null,
  description text not null,
  risk_level text not null check (risk_level in ('High', 'Medium', 'Low')),
  owner_name text not null,
  subject text,
  body text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  decided_at timestamptz
);

create index if not exists conversations_customer_id_idx on public.conversations(customer_id);
create index if not exists agent_runs_customer_id_idx on public.agent_runs(customer_id);
create index if not exists agent_runs_created_at_idx on public.agent_runs(created_at desc);
create index if not exists approvals_status_idx on public.approvals(status);

alter table public.customers enable row level security;
alter table public.conversations enable row level security;
alter table public.customer_usage enable row level security;
alter table public.subscriptions enable row level security;
alter table public.support_tickets enable row level security;
alter table public.agent_runs enable row level security;
alter table public.approvals enable row level security;
